version: '3.4'

services:
  energy-utility-platform-api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
      - "44378:443"
    depends_on:
      - db
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  db:
    container_name: UtilityPlatformContainerDb
    environment:
        SA_PASSWORD: yourStrong(!)Password
        ACCEPT_EULA: "Y"
    restart: always
    ports:
        - "1433:1433"