version: '3.4'

services:
  energy-utility-platform-api:
    image: ${DOCKER_REGISTRY-}energyutilityplatformapi
    build:
      context: .
      dockerfile: energy-utility-platform-api/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
      - "44378:443"
    depends_on:
      - db
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
  db:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=yourStrong(!)Password
    restart: always
    ports:
        - "1433:1433"
    volumes:
      - ./data:/var/opt/mssql/data